# tag::all[]
load(":bazel/application.bzl", "application")

application(
  name="main.zip",
  srcs=[
    "src/main.c",
    "src/print.c",
  ],
  hdrs=[
    "src/print.h",
  ],
  extra_files=[
    "src/README.md",
  ],
)
# end::all[]

