load("//vars:single_variable.bzl", "single_variable")  # <1>

single_variable(name="STABLE_GIT_COMMIT")  # <2>
single_variable(name="CURRENT_TIME")

package(default_visibility = ["//visibility:public"])  # <3>

