# tag::all[]
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")  # <1>

RULES_JVM_EXTERNAL_TAG = "3.2"
RULES_JVM_EXTERNAL_SHA = "82262ff4223c5fda6fb7ff8bd63db8131b51b413d26eb49e3131037e79e324af"

# tag::fetch_maven_install[]
http_archive(  # <2>
# tag::http_archive_definition[]
    name = "rules_jvm_external",
# end::http_archive_definition[]
    strip_prefix = "rules_jvm_external-%s" % RULES_JVM_EXTERNAL_TAG,
    sha256 = RULES_JVM_EXTERNAL_SHA,
    url = "https://github.com/bazelbuild/rules_jvm_external/archive/%s.zip" % RULES_JVM_EXTERNAL_TAG,
)

# tag::maven_install_load[]
load("@rules_jvm_external//:defs.bzl", "maven_install")  # <3>
# end::maven_install_load[]
# end::fetch_maven_install[]

# tag::maven_install[]
maven_install(  # <4>
    artifacts = [
      "org.apache.commons:commons-compress:1.20",
      "commons-io:commons-io:2.7",
      "org.tukaani:xz:1.8",
    ],
    repositories = [
        "https://jcenter.bintray.com/",
        "https://maven.google.com",
        "https://repo1.maven.org/maven2",
    ],
)
# end::maven_install[]

# end::all[]
